package com.drobnyd.drobnyd.service;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import org.springframework.stereotype.Service;

import com.drobnyd.drobnyd.config.properties.PubSubProperties;
import com.drobnyd.drobnyd.entity.Order;
import com.drobnyd.drobnyd.entity.OrderStatus;
import com.drobnyd.drobnyd.service.model.OrderEventMessage;
import com.drobnyd.drobnyd.service.model.OrderEventType;

@Service
public class NotificationService {

    private static final Logger log = LoggerFactory.getLogger(NotificationService.class);

    private final PubSubProperties pubSubProperties;
    private final PubSubEventPublisher pubSubEventPublisher;

    public NotificationService(PubSubProperties pubSubProperties, PubSubEventPublisher pubSubEventPublisher) {
        this.pubSubProperties = pubSubProperties;
        this.pubSubEventPublisher = pubSubEventPublisher;
    }

    public void publishOrderCreated(Order order) {
        publishOrderEvent(
                OrderEventType.ORDER_CREATED,
                order,
                null,
                order.getStatus().name(),
                "Order created",
                null);
    }

    public void publishOrderStatusChanged(Order order, OrderStatus previousStatus) {
        publishOrderEvent(
                OrderEventType.ORDER_STATUS_CHANGED,
                order,
                previousStatus.name(),
                order.getStatus().name(),
                "Order status changed",
                null);
    }

    public void publishWalletDebited(Integer clientId, long amount, long newBalance) {
        log.info("Publishing wallet-debited event for clientId={}, amount={}, newBalance={}",
                clientId,
                amount,
                newBalance);
    }

    public void publishOrderInProgress(Order order, Integer operatorId) {
        publishOrderEvent(
                OrderEventType.ORDER_IN_PROGRESS,
                order,
                null,
                order.getStatus().name(),
                "Order moved to in-progress by operatorId=" + operatorId,
                null);
    }

    public void publishOrderIssueReported(Order order, OrderStatus previousStatus, String reason) {
        publishOrderEvent(
                OrderEventType.ORDER_ISSUE_REPORTED,
                order,
                previousStatus.name(),
                order.getStatus().name(),
                reason,
                null);
    }

    public void publishOrderFileDownloadLinkGenerated(Order order, Integer operatorId, String requestId) {
        publishOrderEvent(
                OrderEventType.ORDER_FILE_DOWNLOAD_LINK_GENERATED,
                order,
                null,
                order.getStatus().name(),
                "Download link generated by operatorId=" + operatorId,
                requestId);
    }

    public void publishStorageObjectFinalized(
            String bucketId,
            String objectPath,
            @Nullable Integer clientId,
            String requestId) {
        OrderEventMessage eventMessage = new OrderEventMessage(
                UUID.randomUUID().toString(),
                OrderEventType.FILE_UPLOADED,
                OffsetDateTime.now(),
                null,
                clientId,
                null,
                null,
                objectPath,
                null,
                null,
                "Storage object finalized in bucket=" + bucketId,
                requestId);

        log.info("Publishing file-uploaded event for objectPath={} clientId={} bucketId={}",
                objectPath,
                clientId,
                bucketId);
        pubSubEventPublisher.publish(
                pubSubProperties.orderEventsTopicName(),
                eventMessage,
                Map.of(
                        "eventType", OrderEventType.FILE_UPLOADED.name(),
                        "bucketId", bucketId == null ? "unknown" : bucketId));
    }

    private void publishOrderEvent(
            OrderEventType eventType,
            Order order,
            @Nullable String previousStatus,
            @Nullable String currentStatus,
            @Nullable String reason,
            @Nullable String requestIdOverride) {
        String requestId = requestIdOverride != null && !requestIdOverride.isBlank()
                ? requestIdOverride
                : resolveRequestId();

        OrderEventMessage eventMessage = new OrderEventMessage(
                UUID.randomUUID().toString(),
                eventType,
                OffsetDateTime.now(),
                order.getOrderId(),
                order.getClient().getClientId(),
                order.getClient().getEmail(),
                order.getPrintingPoint().getPrintingPointId(),
                order.getFilePath(),
                previousStatus,
                currentStatus,
                reason,
                requestId);

        log.info("Publishing {} event for orderId={} clientId={} printingPointId={} requestId={}",
                eventType,
                order.getOrderId(),
                order.getClient().getClientId(),
                order.getPrintingPoint().getPrintingPointId(),
                requestId);

        pubSubEventPublisher.publish(
                pubSubProperties.orderEventsTopicName(),
                eventMessage,
                Map.of(
                        "eventType", eventType.name(),
                        "orderId", String.valueOf(order.getOrderId()),
                        "clientId", String.valueOf(order.getClient().getClientId())));
    }

    private String resolveRequestId() {
        String requestId = MDC.get("requestId");
        return requestId == null || requestId.isBlank() ? "unknown-request" : requestId;
    }
}