--
-- PostgreSQL database dump
--

\restrict IfrLWxkI19GX9aVIIasqxHeYX69dv2oyMog84cvAVwimSWliNKHFb3fQCBZgLcm

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: money_amount; Type: DOMAIN; Schema: public; Owner: postgres
--

CREATE DOMAIN public.money_amount AS bigint
	CONSTRAINT money_amount_check CHECK ((VALUE >= 0));


ALTER DOMAIN public.money_amount OWNER TO postgres;

--
-- Name: DOMAIN money_amount; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON DOMAIN public.money_amount IS 'Kwota przechowywana w groszach (1 PLN = 100 groszy)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    client_id integer NOT NULL,
    email character varying(255) NOT NULL,
    firebase_uid character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    status character varying(50) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- Name: clients_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN client_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: extra_pricing; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.extra_pricing (
    printing_point_id integer NOT NULL,
    binding_price public.money_amount DEFAULT 0 NOT NULL,
    stapling_price public.money_amount DEFAULT 0 NOT NULL,
    cover_price public.money_amount DEFAULT 0 NOT NULL
);


ALTER TABLE public.extra_pricing OWNER TO postgres;

--
-- Name: opening_hours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.opening_hours (
    printing_point_id integer NOT NULL,
    day_of_week integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    CONSTRAINT opening_hours_day_of_week_check CHECK (((day_of_week >= 1) AND (day_of_week <= 7)))
);


ALTER TABLE public.opening_hours OWNER TO postgres;

--
-- Name: operators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operators (
    operator_id integer NOT NULL,
    printing_point_id integer NOT NULL,
    firebase_uid character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    employee_number character varying(100) NOT NULL,
    role character varying(50) NOT NULL,
    status character varying(50) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.operators OWNER TO postgres;

--
-- Name: operators_operator_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.operators ALTER COLUMN operator_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operators_operator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    order_id integer NOT NULL,
    printing_point_id integer NOT NULL,
    client_id integer NOT NULL,
    file_path text NOT NULL,
    page_count integer NOT NULL,
    total_price public.money_amount NOT NULL,
    pickup_at timestamp with time zone NOT NULL,
    status character varying(50) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT orders_page_count_check CHECK ((page_count > 0))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: print_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.print_settings (
    order_id integer NOT NULL,
    format character varying(50) NOT NULL,
    paper_type character varying(50) NOT NULL,
    color_mode character varying(50) NOT NULL,
    duplex character varying(50) NOT NULL,
    orientation character varying(50) NOT NULL,
    finishing character varying(50) NOT NULL,
    copies integer NOT NULL,
    CONSTRAINT print_settings_copies_check CHECK ((copies >= 1))
);


ALTER TABLE public.print_settings OWNER TO postgres;

--
-- Name: printing_points; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.printing_points (
    printing_point_id integer NOT NULL,
    name character varying(255) NOT NULL,
    street_address character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    postal_code character varying(20) NOT NULL,
    country character varying(100) NOT NULL,
    hourly_order_limit integer NOT NULL,
    CONSTRAINT printing_points_hourly_order_limit_check CHECK ((hourly_order_limit >= 1))
);


ALTER TABLE public.printing_points OWNER TO postgres;

--
-- Name: printing_points_printing_point_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.printing_points ALTER COLUMN printing_point_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.printing_points_printing_point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: printouts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.printouts (
    order_id integer NOT NULL,
    operator_id integer NOT NULL,
    printed_at timestamp with time zone NOT NULL
);


ALTER TABLE public.printouts OWNER TO postgres;

--
-- Name: rate_sheets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rate_sheets (
    printing_point_id integer NOT NULL,
    paper_type character varying(50) NOT NULL,
    format character varying(50) NOT NULL,
    page_price public.money_amount NOT NULL,
    CONSTRAINT rate_sheets_page_price_check CHECK (((page_price)::bigint > 0))
);


ALTER TABLE public.rate_sheets OWNER TO postgres;

--
-- Name: wallet_top_ups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_top_ups (
    top_up_id integer NOT NULL,
    client_id integer NOT NULL,
    amount public.money_amount NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT wallet_top_ups_amount_check CHECK (((amount)::bigint > 0))
);


ALTER TABLE public.wallet_top_ups OWNER TO postgres;

--
-- Name: wallet_top_ups_top_up_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_top_ups ALTER COLUMN top_up_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_top_ups_top_up_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallets (
    client_id integer NOT NULL,
    balance public.money_amount DEFAULT 0 NOT NULL,
    status character varying(50) DEFAULT 'ACTIVE'::character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.wallets OWNER TO postgres;

--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clients (client_id, email, firebase_uid, first_name, last_name, status, created_at, updated_at) FROM stdin;
1	anna.kowalska@example.com	firebase_client_anna_kowalska	Anna	Kowalska	ACTIVE	2026-06-04 11:16:20.269822+00	2026-06-04 11:16:20.269822+00
2	jan.nowak@example.com	firebase_client_jan_nowak	Jan	Nowak	ACTIVE	2026-06-04 11:16:20.269822+00	2026-06-04 11:16:20.269822+00
3	marta.wisniewska@example.com	firebase_client_marta_wisniewska	Marta	Wiśniewska	BLOCKED	2026-06-04 11:16:20.269822+00	2026-06-04 11:16:20.269822+00
\.


--
-- Data for Name: extra_pricing; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.extra_pricing (printing_point_id, binding_price, stapling_price, cover_price) FROM stdin;
1	800	150	500
2	1000	100	600
\.


--
-- Data for Name: opening_hours; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.opening_hours (printing_point_id, day_of_week, start_time, end_time) FROM stdin;
1	1	08:00:00	18:00:00
1	2	08:00:00	18:00:00
1	3	08:00:00	18:00:00
1	4	08:00:00	18:00:00
1	5	08:00:00	18:00:00
1	6	10:00:00	14:00:00
2	1	09:00:00	17:00:00
2	2	09:00:00	17:00:00
2	3	09:00:00	17:00:00
2	4	09:00:00	17:00:00
2	5	09:00:00	15:00:00
\.


--
-- Data for Name: operators; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operators (operator_id, printing_point_id, firebase_uid, email, employee_number, role, status, created_at, updated_at) FROM stdin;
1	1	firebase_operator_adam_zielinski	adam.zielinski@drobnyd.pl	EMP-CEN-001	ADMIN	ACTIVE	2026-06-04 11:16:20.275855+00	2026-06-04 11:16:20.275855+00
2	1	firebase_operator_ewa_lis	ewa.lis@drobnyd.pl	EMP-CEN-002	EMPLOYEE	ACTIVE	2026-06-04 11:16:20.275855+00	2026-06-04 11:16:20.275855+00
3	2	firebase_operator_tomasz_wrobel	tomasz.wrobel@drobnyd.pl	EMP-POL-001	ADMIN	ACTIVE	2026-06-04 11:16:20.275855+00	2026-06-04 11:16:20.275855+00
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (order_id, printing_point_id, client_id, file_path, page_count, total_price, pickup_at, status, created_at, updated_at) FROM stdin;
1	1	1	orders/1/praca-dyplomowa.pdf	52	2600	2026-06-05 08:00:00+00	PENDING	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
2	1	2	orders/2/prezentacja.pdf	24	2880	2026-06-05 09:00:00+00	READY	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
3	2	1	orders/3/notatki.pdf	180	8100	2026-06-05 11:00:00+00	APPROVED	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
4	1	3	orders/4/ulotka.pdf	2	1320	2026-06-06 10:00:00+00	CANCELLED	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
5	2	2	orders/5/instrukcja.pdf	36	3420	2026-06-05 12:00:00+00	DISPENSED	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
6	1	1	orders/6/cv.pdf	3	150	2026-06-04 14:00:00+00	READY	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
7	2	2	orders/7/skrypt.pdf	120	11400	2026-06-06 09:00:00+00	APPROVED	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
8	1	1	orders/8/plakat.pdf	1	220	2026-06-06 11:00:00+00	PENDING	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
9	2	3	orders/9/regulamin.pdf	14	630	2026-06-07 08:00:00+00	APPROVED	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
10	1	2	orders/10/oferta.pdf	48	9120	2026-06-07 13:00:00+00	READY	2026-06-04 11:16:20.278927+00	2026-06-04 11:16:20.278927+00
\.


--
-- Data for Name: print_settings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.print_settings (order_id, format, paper_type, color_mode, duplex, orientation, finishing, copies) FROM stdin;
1	A4	standardowy	GRAYSCALE	DOUBLE_SIDED	PORTRAIT	NONE	1
2	A4	błyszczący	COLOR	SINGLE_SIDED	LANDSCAPE	STAPLING	1
3	A4	standardowy	GRAYSCALE	DOUBLE_SIDED	PORTRAIT	BINDING	2
4	A5	błyszczący	COLOR	SINGLE_SIDED	LANDSCAPE	NONE	10
5	A4	matowy	GRAYSCALE	DOUBLE_SIDED	PORTRAIT	COVER	3
6	A4	standardowy	GRAYSCALE	SINGLE_SIDED	PORTRAIT	NONE	1
7	A4	matowy	COLOR	DOUBLE_SIDED	PORTRAIT	BINDING	2
8	A3	błyszczący	COLOR	SINGLE_SIDED	LANDSCAPE	NONE	1
9	A4	standardowy	GRAYSCALE	DOUBLE_SIDED	PORTRAIT	NONE	1
10	A3	kredowy	COLOR	SINGLE_SIDED	LANDSCAPE	STAPLING	2
\.


--
-- Data for Name: printing_points; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.printing_points (printing_point_id, name, street_address, city, postal_code, country, hourly_order_limit) FROM stdin;
1	Drobny Druk Centrum	Piotrkowska 123/5	Łódź	90-001	Polska	12
2	Drobny Druk Politechnika	Wólczańska 215	Łódź	93-005	Polska	8
\.


--
-- Data for Name: printouts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.printouts (order_id, operator_id, printed_at) FROM stdin;
2	2	2026-06-04 13:20:00+00
5	3	2026-06-04 07:15:00+00
6	1	2026-06-04 13:10:00+00
10	2	2026-06-05 15:40:00+00
\.


--
-- Data for Name: rate_sheets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rate_sheets (printing_point_id, paper_type, format, page_price) FROM stdin;
1	standardowy	A5	30
1	standardowy	A4	50
1	standardowy	A3	100
1	błyszczący	A5	70
1	błyszczący	A4	120
1	błyszczący	A3	220
1	matowy	A5	60
1	matowy	A4	100
1	matowy	A3	190
1	kredowy	A5	80
1	kredowy	A4	140
1	kredowy	A3	260
2	standardowy	A5	25
2	standardowy	A4	45
2	standardowy	A3	90
2	błyszczący	A5	65
2	błyszczący	A4	110
2	błyszczący	A3	210
2	matowy	A5	55
2	matowy	A4	95
2	matowy	A3	180
2	kredowy	A5	75
2	kredowy	A4	130
2	kredowy	A3	250
\.


--
-- Data for Name: wallet_top_ups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wallet_top_ups (top_up_id, client_id, amount, created_at) FROM stdin;
1	1	10000	2026-06-04 11:16:20.272937+00
2	1	10000	2026-06-04 11:16:20.272937+00
3	2	30000	2026-06-04 11:16:20.272937+00
4	3	5000	2026-06-04 11:16:20.272937+00
\.


--
-- Data for Name: wallets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wallets (client_id, balance, status, updated_at) FROM stdin;
1	8930	ACTIVE	2026-06-04 11:16:20.271498+00
2	3180	ACTIVE	2026-06-04 11:16:20.271498+00
3	5000	BLOCKED	2026-06-04 11:16:20.271498+00
\.


--
-- Name: clients_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clients_client_id_seq', 1, false);


--
-- Name: operators_operator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operators_operator_id_seq', 1, false);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 1, false);


--
-- Name: printing_points_printing_point_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.printing_points_printing_point_id_seq', 1, false);


--
-- Name: wallet_top_ups_top_up_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wallet_top_ups_top_up_id_seq', 1, false);


--
-- Name: clients clients_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_email_key UNIQUE (email);


--
-- Name: clients clients_firebase_uid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_firebase_uid_key UNIQUE (firebase_uid);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (client_id);


--
-- Name: extra_pricing extra_pricing_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.extra_pricing
    ADD CONSTRAINT extra_pricing_pkey PRIMARY KEY (printing_point_id);


--
-- Name: opening_hours opening_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.opening_hours
    ADD CONSTRAINT opening_hours_pkey PRIMARY KEY (printing_point_id, day_of_week);


--
-- Name: operators operators_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_email_key UNIQUE (email);


--
-- Name: operators operators_employee_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_employee_number_key UNIQUE (employee_number);


--
-- Name: operators operators_firebase_uid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_firebase_uid_key UNIQUE (firebase_uid);


--
-- Name: operators operators_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_pkey PRIMARY KEY (operator_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: print_settings print_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.print_settings
    ADD CONSTRAINT print_settings_pkey PRIMARY KEY (order_id);


--
-- Name: printing_points printing_points_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.printing_points
    ADD CONSTRAINT printing_points_pkey PRIMARY KEY (printing_point_id);


--
-- Name: printouts printouts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.printouts
    ADD CONSTRAINT printouts_pkey PRIMARY KEY (order_id);


--
-- Name: rate_sheets rate_sheets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rate_sheets
    ADD CONSTRAINT rate_sheets_pkey PRIMARY KEY (printing_point_id, paper_type, format);


--
-- Name: wallet_top_ups wallet_top_ups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_top_ups
    ADD CONSTRAINT wallet_top_ups_pkey PRIMARY KEY (top_up_id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (client_id);


--
-- Name: extra_pricing extra_pricing_printing_point_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.extra_pricing
    ADD CONSTRAINT extra_pricing_printing_point_id_fkey FOREIGN KEY (printing_point_id) REFERENCES public.printing_points(printing_point_id);


--
-- Name: opening_hours opening_hours_printing_point_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.opening_hours
    ADD CONSTRAINT opening_hours_printing_point_id_fkey FOREIGN KEY (printing_point_id) REFERENCES public.printing_points(printing_point_id);


--
-- Name: operators operators_printing_point_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operators
    ADD CONSTRAINT operators_printing_point_id_fkey FOREIGN KEY (printing_point_id) REFERENCES public.printing_points(printing_point_id);


--
-- Name: orders orders_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id);


--
-- Name: orders orders_printing_point_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_printing_point_id_fkey FOREIGN KEY (printing_point_id) REFERENCES public.printing_points(printing_point_id);


--
-- Name: print_settings print_settings_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.print_settings
    ADD CONSTRAINT print_settings_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id);


--
-- Name: printouts printouts_operator_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.printouts
    ADD CONSTRAINT printouts_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.operators(operator_id);


--
-- Name: printouts printouts_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.printouts
    ADD CONSTRAINT printouts_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id);


--
-- Name: rate_sheets rate_sheets_printing_point_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rate_sheets
    ADD CONSTRAINT rate_sheets_printing_point_id_fkey FOREIGN KEY (printing_point_id) REFERENCES public.printing_points(printing_point_id);


--
-- Name: wallet_top_ups wallet_top_ups_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_top_ups
    ADD CONSTRAINT wallet_top_ups_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.wallets(client_id);


--
-- Name: wallets wallets_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id);


--
-- PostgreSQL database dump complete
--

\unrestrict IfrLWxkI19GX9aVIIasqxHeYX69dv2oyMog84cvAVwimSWliNKHFb3fQCBZgLcm

