spring.application.name=drobnyd
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-},requestId=%X{requestId:-}]
logging.include-application-name=false
management.otlp.metrics.export.enabled=false
management.otlp.tracing.export.enabled=false
