spring.application.name=drobnyd
spring.profiles.default=local
spring.jpa.open-in-view=false
server.port=${PORT:8080}

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [requestId=%X{requestId:-none}] [traceId=%X{traceId:-none}] %logger{36} : %msg%n

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs