spring.application.name=drobnyd
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-},requestId=%X{requestId:-}]
logging.include-application-name=false
management.otlp.metrics.export.enabled=false
management.otlp.tracing.export.enabled=false
springdoc.api-docs.version=OPENAPI_3_1

# Ustawienia serwera SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=drobnyd.home@gmail.com
spring.mail.password=

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Ustawienia połączenia z bazą PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5433/drobnyd

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true